search_services: # List all Cortex Search services
  - service_name: "SNOWFLAKE_DOCS"
    description: "Search service that is connected to Snowflake Documentation and can serve as a guide for all Snowflake related questions."
    database_name: "SNOWDOCS"
    schema_name: "SNOWFLAKE_DOCUMENTATION"